profiles:
  common:
    include:
      - base/common
      - base/salt-minion
      - base/sle
      - products/sles
  Azure:
    description: Azure configuration
    include:
      - csp/azure/addon/azure-tools
  EC2-HVM:
    description: EC2 HVM configuration
    include:
      - csp/ec2/addon/aws-tools
  GCE:
    description: GCE configuration
    include:
      - csp/gce/addon/gce-tools
