profiles:
  common:
    include:
      - base/jeos
      - base/sles
  Azure:
    description: Azure configuration
    include:
      - csp/azure
  EC2-HVM:
    description: EC2 HVM configuration
    include:
      - csp/ec2/addon/aws-tools
  GCE:
    description: GCE configuration
    include:
      - csp/gce
