profiles:
  common:
    include:
      - base/cloudreg
      - base/common
      - base/sle-modules
      - base/sle
      - products/sles
  Azure:
    include:
      - csp/azure/addon/azure-kernel
      - csp/azure/addon/azure-tools
      - csp/azure/ondemand
    Azure-Basic:
      description: Azure configuration
      include:
        - csp/azure/ondemand/basic
    Azure-Standard:
      description: Azure configuration
      include:
        - csp/azure/ondemand/standard
  EC2:
    description: EC2 configuration
    include:
      - csp/ec2/addon/aws-tools
      - csp/ec2/ondemand
  GCE:
    description: GCE configuration
    include:
      - csp/gce/addon/gce-tools
      - csp/gce/ondemand/sles
