image:
  profiles:
    _namespace_profiles_base:
      profile:
        - _attributes:
            name: azure-base
            description: Base profile for Microsoft Azure
        - _attributes:
            name: ec2-base
            description: Base profile for Amazon EC2
        - _attributes:
            name: gce-base
            description: Base profile for Google Compute
    _namespace_profiles_azure:
      profile:
        - _attributes:
            name: Azure
            description: Configuration for Microsoft Azure
          requires:
            - _attributes:
                profile: azure-base
    _namespace_profiles_standard:
      profile:
        - _attributes:
            name: EC2
            description: Configuration for Amazon EC2
          requires:
            - _attributes:
                profile: ec2-base
        - _attributes:
            name: GCE
            description: Configuration for Google Compute
          requires:
            - _attributes:
                profile: gce-base
  preferences:
    - _include:
        - base/common
  _namespace_preferences_root:
    _namespace_preferences_azure:
      preferences:
        - _attributes:
            profiles: [Azure]
            arch: x86_64
          _include:
            - platforms/csp/azure/x86_64
        - _attributes:
            profiles: [Azure]
            arch: aarch64
          _include:
            - platforms/csp/azure/aarch64
    _namespace_preferences_standard:
      preferences:
        - _attributes:
            profiles: [EC2]
            arch: x86_64
          _include:
            - platforms/csp/ec2/x86_64
        - _attributes:
            profiles: [EC2]
            arch: aarch64
          _include:
            - platforms/csp/ec2/aarch64
        - _attributes:
            profiles: [GCE]
            arch: x86_64
          _include:
            - platforms/csp/gce/x86_64
        - _attributes:
            profiles: [GCE]
            arch: aarch64
          _include:
            - platforms/csp/gce/aarch64
  _namespace_packages_root:
    _namespace_packages_base:
      packages:
        - _attributes:
            type: bootstrap
          _include:
            - base/bootstrap
        - _attributes:
            type: image
          _include:
            - base/bootloader
            - base/common
            - products
        - _attributes:
            type: image
            profiles:
              - azure-base
              - ec2-base
              - gce-base
          _include:
            - base/pubcloud
          archive:
            - _attributes:
                name: pubcloud.tar.gz
        - _attributes:
            type: image
            profiles: [azure-base]
          _include:
            - platforms/csp/azure
          archive:
            - _attributes:
                name: azure.tar.gz
        - _attributes:
            type: image
            profiles: [ec2-base]
          _include:
            - platforms/csp/ec2
          archive:
            - _attributes:
                name: ec2.tar.gz
        - _attributes:
            type: image
            profiles: [gce-base]
          _include:
            - platforms/csp/gce
          archive:
            - _attributes:
                name: gce.tar.gz
config:
  - _include:
      - base/common
      - products
  - profiles:
      - azure-base
      - ec2-base
      - gce-base
    _include:
      - base/pubcloud
  - profiles: [azure-base]
    _include:
      - platforms/csp/azure
  - profiles: [ec2-base]
    _include:
      - platforms/csp/ec2
  - profiles: [gce-base]
    _include:
      - platforms/csp/gce
archive:
  - name: root.tar.gz
    _include:
      - products
  - name: pubcloud.tar.gz
    _include:
      - base/pubcloud
  - name: azure.tar.gz
    _include:
      - platforms/csp/azure
  - name: ec2.tar.gz
    _include:
      - platforms/csp/ec2
  - name: gce.tar.gz
    _include:
      - platforms/csp/gce
