profiles:
  common:
    include:
      - base/cloudreg
      - base/common
      - base/sle
      - base/sle-modules
      - csp/azure/addon/azure-tools
      - csp/azure/addon/cloudreg-switch
      - csp/azure/ondemand/sap
      - products/sap/ondemand
