profiles:
  common:
    include:
      - base/common
      - base/sle
      - products/sap
      - products/sap/azure-baremetal
  azure-vli:
    include:
      - csp/azure-baremetal/vli
    Devel:
      description: Devel Image Build
      include:
        - csp/azure-baremetal/vli/devel
    Production:
      description: Production Image Build
      include:
        - csp/azure-baremetal/vli
