profiles:
  common:
    include:
      - base/jeos
      - base/sles
      - products/suse-manager/proxy
  Azure:
    include:
      - csp/azure
  EC2-HVM:
    include:
      - csp/ec2
  GCE:
    include:
      - csp/gce
