profiles:
  common:
    include:
      - base/common
      - base/sle
  Base-BYOS:
    include:
      - csp/gce/addon/gce-tools
    BYOS:
      description: SLES GCE On-Demand configuration
      include:
        - csp/gce/addon/gce-tools
        - products/sles/byos
    SAP-BYOS:
      description: SLES of SAP GCE BYOS configuration
      include:
        - csp/gce/addon/gce-tools
        - products/sap/byos
  Base-On-Demand:
    include:
      - base/cloudreg
      - base/sle-modules
      - csp/gce/addon/gce-tools
      - csp/gce/ondemand
    On-Demand:
      description: SLES GCE BYOS configuration
      include:
        - csp/gce/ondemand
        - products/sles/ondemand
    SAP-On-Demand:
      description: SLES of SAP GCE On-Demand configuration
      include:
        - csp/gce/ondemand
        - products/sap/ondemand
