profiles:
  common:
    include:
      - base/common
      - base/sle
      - products/sap/byos
  Devel:
    description: Devel Image Build
    include:
      - csp/azure-baremetal/vli/devel
  Production:
    description: Production Image Build
    include:
      - csp/azure-baremetal/vli
