#!/bin/sh
set -e

cat << EOF
set linux=linux
set initrd=initrd
if [ "\${grub_cpu}" = "x86_64" -o "\${grub_cpu}" = "i386" ];then
    if [ "\${grub_platform}" = "efi" ]; then
        set linux=linuxefi
        set initrd=initrdefi
    fi
fi
EOF
