profiles:
  common:
    include:
      - base/cloudreg
      - base/common
      - base/sle-modules
      - base/sle
      - products/sapcal
      - products/sles
  Azure:
    description: Azure configuration
    include:
      - csp/azure/addon/azure-tools
      - csp/azure/ondemand/basic
  EC2:
    description: EC2 configuration
    include:
      - csp/ec2/addon/aws-tools
      - csp/ec2/ondemand
  GCE:
    description: GCE configuration
    include:
      - csp/gce/addon/gce-tools
      - csp/gce/ondemand
