profiles:
  common:
    include:
      - base/common
  Base-BYOS:
    include:
      - base/sle
      - csp/ec2/addon/aws-tools
    BYOS:
      include:
        - products/sles/byos
    SAP-BYOS:
      include:
        - products/sap/byos
  Base-On-Demand:
    include:
      - base/cloudreg
      - base/sle-modules
      - csp/ec2/ondemand
    ECS-On-Demand:
      include:
        - csp/ec2/addon/ecs
        - products/sles/ondemand
    On-Demand:
      include:
        - base/sle
        - csp/ec2/addon/aws-tools
        - products/sles/ondemand
    SAP-On-Demand:
      include:
        - base/sle
        - csp/ec2/addon/aws-tools
        - products/sap/ondemand
