profiles:
  common:
    include:
      - base/common
      - base/sle
  Base-On-Demand:
    include:
      - base/cloudreg
      - base/sle-modules
      - csp/azure/addon/azure-tools
      - csp/azure/ondemand
    Basic-On-Demand:
      description: SLES Basic On-Demand image
      include:
        - csp/azure/addon/azure-kernel
        - csp/azure/ondemand/basic
        - products/sles/ondemand
    Standard-On-Demand:
      description: SLES Standard On-Demand image
      include:
        - csp/azure/addon/azure-kernel
        - products/sles/ondemand
    HPC-On-Demand:
      description: SLES HPC On-Demand image
      include:
        - csp/azure/addon/azure-kernel
        - csp/azure/addon/waagent-rdma
        - products/hpc/ondemand
    SAP-On-Demand:
      description: SLES for SAP On-Demand image
      include:
        - csp/azure/addon/azure-tools
        - products/sap/ondemand
  Base-BYOS:
    include:
      - csp/azure/addon/azure-tools
    BYOS:
      description: SLES BYOS image
      include:
        - products/sles/byos
    HPC-BYOS:
      description: SLES HPC BYOS image
      include:
        - csp/azure/addon/waagent-rdma
        - products/hpc/byos
    SAP-BYOS:
      description: SLES for SAP BYOS image
      include:
        - products/sap/byos
