profiles:
  common:
    include:
      - base/common
      - base/sle
      - products/suse-manager/server
  Azure:
    include:
      - csp/azure/addon/azure-tools
  EC2:
    include:
      - csp/ec2/addon/aws-tools
  GCE:
    include:
      - csp/gce/addon/gce-tools
