profiles:
  common:
    include:
      - base/cloudreg
      - base/common
      - base/sle
      - base/sle-modules
      - csp/ec2/addon/aws-sap
      - csp/ec2/addon/aws-tools
      - csp/ec2/ondemand
      - products/sap/addon/hana-net
      - products/sap/ondemand
