profiles:
  EC2-ECS-HVM:
    include:
      - base/cloudreg
      - base/jeos
      - base/sle-modules
      - base/sles
      - csp/ec2/addon/aws-tools
      - csp/ec2/addon/ecs
      - csp/ec2/ondemand
