profiles:
  common:
    include:
      - base/cloudreg
      - base/common
      - base/sle-modules
      - csp/ec2/addon/aws-tools
      - csp/ec2/addon/ecs
      - csp/ec2/ondemand
      - products/sles
