profiles:
  common:
    include:
      - base/common
      - products/chost
  Aliyun:
    description: Alibaba Cloud configuration
    include:
      - csp/aliyun
      - kernel-options/cgroup-memory
  Azure:
    description: Azure configuration
    include:
      - csp/azure/addon/chost-tweaks
      - kernel-options/cgroup-memory
  EC2:
    description: EC2 configuration
    include:
      - csp/ec2
      - kernel-options/cgroup-memory
  GCE:
    description: GCE configuration
    include:
      - csp/gce
      - kernel-options/cgroup-memory
  OpenStack:
    description: OpenStack configuration
    include:
      - csp/openstack
      - kernel-options/cgroup-memory
