profiles:
  common:
    include:
      - base/jeos
      - products/chost
  Aliyun:
    description: Alibaba Cloud configuration
    include:
      - csp/aliyun
  Azure:
    description: Azure configuration
    include:
      - csp/azure
  EC2-HVM:
    description: EC2 HVM configuration
    include:
      - csp/ec2
  GCE:
    description: GCE configuration
    include:
      - csp/gce
