profiles:
  common:
    include:
      - base/jeos
      - base/sle
      - products/sap/byos
  Azure:
    description: Azure configuration
    include:
      - csp/azure/addon/azure-tools
  EC2-HVM:
    description: EC2 HVM configuration
    include:
      - csp/ec2/addon/aws-tools
  GCE:
    description: GCE configuration
    include:
      - csp/gce/addon/fence-agent-deps
      - csp/gce/addon/gce-tools
      - csp/gce/addon/google-auth
