profiles:
  common:
    include:
      - base/hpc
      - base/common
      - base/salt-minion
      - base/sle
      - products/hpc
  Azure:
    description: Azure configuration
    include:
      - csp/azure/addon/azure-tools
  EC2-HVM:
    description: EC2 HVM configuration
    include:
      - csp/ec2/addon/aws-tools
