profiles:
  common:
    include:
      - base/common
      - base/sle
      - products/sles/byos
  Azure:
    description: Azure configuration
    include:
      - csp/azure/addon/azure-tools
      - csp/azure/byos/sles
  EC2:
    description: EC2 configuration
    include:
      - csp/ec2/addon/aws-tools
  GCE:
    description: GCE configuration
    include:
      - csp/gce/addon/gce-tools
      - csp/gce/byos/sles
