profiles:
  common:
    include:
      - base/common
      - base/sle
      - csp/azure/addon/azure-tools
      - csp/azure/addon/cloudreg-switch
      - csp/azure/addon/waagent-rdma
      - csp/azure/byos/hpc
      - products/hpc/byos
