profiles:
  common:
    include:
      - base/jeos
      - base/sles
      - products/suse-manager/server
  Azure:
    include:
      - csp/azure
  EC2-HVM:
    include:
      - csp/ec2
      - csp/ec2/addon/aws-tools
  GCE:
    include:
      - csp/gce
