profiles:
  common:
    include:
      - base/hpc
      - base/common
      - base/sle-modules
      - base/sle
      - products/hpc/ondemand
  Azure:
    description: Azure configuration
    include:
      - csp/azure/addon/azure-kernel
      - csp/azure/addon/azure-tools
      - csp/azure/addon/waagent-rdma
      - csp/azure/ondemand/hpc
  EC2:
    description: EC2 configuration
    include:
      - csp/ec2/addon/aws-tools
      - csp/ec2/ondemand
  GCE:
    description: GCE configuration
    include:
      - csp/gce/addon/gce-tools
      - csp/gce/ondemand/hpc
