profiles:
  common:
    include:
      - base/common
      - base/sle
      - base/sle-modules
      - products/sap/ondemand
  Azure:
    include:
      - csp/azure/addon/azure-tools
      - csp/azure/ondemand/sap
  EC2:
    include:
      - csp/ec2/addon/aws-tools
      - csp/ec2/ondemand
  GCE:
    include:
      - csp/gce/addon/fence-agent-deps
      - csp/gce/addon/gce-tools
      - csp/gce/addon/google-auth
      - csp/gce/ondemand/sap
