profiles:
  common:
    include:
      - base/common
      - base/sle
      - products/sap/byos
  Azure:
    description: Azure configuration
    include:
      - csp/azure/addon/azure-tools
      - csp/azure/addon/cloudreg-switch
      - csp/azure/byos/sap
  EC2:
    description: EC2 configuration
    include:
      - csp/ec2/addon/aws-tools
  GCE:
    description: GCE configuration
    include:
      - csp/gce/addon/fence-agent-deps
      - csp/gce/addon/gce-tools
      - csp/gce/addon/google-auth
      - csp/gce/byos/sap
